export const WordList = [
    "Dutch Master",
    'Game 2/.99¢',
    'Swisher',
    'Bluntville',
    'Zig Zag 2pk',
    'Zig Zag 4pk',
    'White Owl',
    'Phillies 2/.99¢',
    'Goodtimes Box',
    'Sweet Woods 2/.99¢',
    'HD 3/.99¢',
    'B&M Upright',
    'B&M 5pk',
    'Little N\' Wild',
    'Djarum',
    'Chew',
    'General Goods',
    'Snuff',
    'Shirts',
    'Al Capone',
    'American Club',
    'Cherokee Cigars',
    'Seneca Cigars',
    'Marlboro',
    'Maverick',
    'FF 100',
    'FF Short',
    'Blue 100',
    'Blue Short',
    'Menthol 100',
    'Menthol Short',
    'Red',
    'Silver',
    'Diamond',
    'Green',
    'Mango',
    'Duos',
    'Pineapple',
    'Grape',
    'Russian Cream',
    'Hookah Tobacco 250g',
    'Al Fakher 250g',
    'Hookah Tobacco 50g',
    'Al Fakher 50g',
    'High Hemp',
    'Ez Roll',
    'XXL',
    'Billionaire',
    'Hemp Zone',
    'Hemp Zone Cigarettes',
    'Pure Hemp Smokes',
    'Palma Trio',
    'Pink Diva',
    'Triple Vanilla',
    'Sweet',
    'Green Sweet',
    'Golden Honey',
    'Backwoods',
    'Honey Berry',
    'Black Russian',
    'Dark Stout',
    'Honey Bourbon',
    'Palma',
    'Menthol',
    '55ct Palma',
    '4pk Palma',
    '3pk Palma',
    '3pk Russian Cream',
    'Game Mini',
    'Game Leaf 2pk',
    'Game Leaf 4pk',
    'Blue'
]

export default WordList;